### ISSUE TITLE
About inference

### ISSUE THREAD

**Issue by YCheno** [srihari-humbarwadi/srgan_tensorflow#1]
Hi, I have run the train_srgan.py, and obtained the model_files, however, when I run the inference.py, it occurs error: OSError:SaveModel file does not exist at...
I have confirmed the model path, but it still occurs that error.
Could you please give the test usage? How can I run the inference.py? Thank you!

**Comment by srihari-humbarwadi** [comment]
You need to specify the directory containing the saved_model . Can you please show me the arguments that you are passing to the inference.py script

**Comment by YCheno** [comment]
'python inference.py --input_image '1.png' --saved_model_dir model_files/srgan/'
In the training phase, I used the default arguments, hence ,the model is saved in 'model_files'
![图片1](https://user-images.githubusercontent.com/36029099/158953442-614aefbf-dba0-477f-934f-a320e11d480c.png)

**Comment by srihari-humbarwadi** [comment]
Use the export_saved_model.ipynb notebook to first generate the `saved_model`, then proceed to run the inference.py script

**Comment by YCheno** [comment]
Thanks
